# Generated by Django 3.2.4 on 2021-06-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarista',
            name='cep',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
