# Generated by Django 3.2.4 on 2021-06-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_diarista_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarista',
            name='telefone',
            field=models.CharField(max_length=11),
        ),
    ]
